baseData.push (

    ["Why do black men love white women", "The same reason why White men love Black women, proximity and exposure.", ""],
    ["Why do people think Black men are dangerous", "This perception is rooted in historical and systemic racism, which perpetuates negative stereotypes and criminalization of Black bodies", ""],
    ["Why do Black women often face microaggressions at work", "Microaggressions are a manifestation of underlying biases and systemic inequalities. Black women frequently encounter these due to pervasive stereotypes and institutionalized racism that affect their professional environments", ""],
    ["Why is there a stigma around mental health in the Black community", "The stigma often stems from a history of mistrust in medical institutions and cultural norms that prioritize resilience and self-reliance. Addressing mental health requires breaking down these barriers and fostering supportive environments.", ""],
    ["Why do Black families value education so highly", "Education is seen as a vital pathway to success and a means of overcoming systemic barriers. For many Black families, it represents an opportunity to advance and challenge historical inequalities.", ""],
    ["Why is there a focus on skin tone within the Black community", "Skin tone issues are often a reflection of internalized racism and historical colorism. Addressing these issues involves confronting and dismantling the long-standing biases that divide communities", ""],
    ["Why do some people think Black culture is monolithic", "Viewing Black culture as monolithic disregards its rich diversity. Black communities are varied and multifaceted, with distinct traditions, experiences, and perspectives shaped by different histories and environments", ""],
    ["Why are Black entrepreneurs often overlooked in mainstream business", "Systemic barriers, including limited access to capital and networks, contribute to the underrepresentation of Black entrepreneurs. Advocating for equitable opportunities and support can help address this disparity", ""],
    ["Why do some people think Black art is only about struggle", "This perspective fails to recognize the full spectrum of Black creativity, which encompasses joy, innovation, and diverse experiences. Black art reflects a wide range of human emotions and experiences beyond just struggle", ""],
    ["Why are Black men sometimes portrayed as absent fathers", "This stereotype overlooks the systemic issues that impact family dynamics, including economic challenges and institutional racism. Many Black men are actively involved in their childrens lives despite these obstacles", ""],
    ["Why do Black people often feel a need to 'prove' themselves", "This need stems from societal pressures and biases that unfairly scrutinize Black individuals' achievements. Proving oneself is a response to a culture that often undervalues or questions Black excellence", ""],
    ["Why are Black voices sometimes marginalized in conversations about race", "Marginalization occurs due to systemic power imbalances and a lack of representation. Amplifying Black voices involves actively listening, prioritizing their perspectives, and ensuring they have a seat at the table", ""],
    ["Why do stereotypes about Black people persist despite progress", "Stereotypes persist due to deeply ingrained societal prejudices and a lack of comprehensive education about diverse Black experiences. Continuous effort to challenge and educate is essential for overcoming these outdated views", ""],
    ["Why are Black experiences often excluded from historical narratives", "Historical narratives have traditionally centered on dominant groups, often excluding or distorting Black experiences. Inclusive history requires revising narratives to fully represent the contributions and experiences of Black individuals", ""],
    ["Why do some people claim Black Lives Matter is divisive", "The Black Lives Matter movement seeks to address systemic injustices and inequality. Claims of divisiveness often stem from discomfort with confronting uncomfortable truths about racial disparities", ""],
    ["Why do Black people sometimes feel disconnected from mainstream culture", "Disconnection can arise from systemic exclusion and the lack of representation in mainstream media and cultural institutions. Bridging this gap involves fostering more inclusive and diverse cultural narratives", ""],    
  ["crycella freitag", "Here are pending legal documents: https://drive.google.com/file/d/1ztjk8LZ8lTjma0Z9szn_wUlrySPFtno3/view\nhttps://drive.google.com/file/d/1sZVLOM2lNEmYxjg4KUtdRFWzNTjVxFMN/view\nhttps://drive.google.com/file/d/1pjIVi5Ao3huyPE7E1FRxo52T8l9xe3xX/view\nhttps://drive.google.com/file/d/1DGp9Sd5-3Be3f_sdyzULVf2epqIGCdew/view", ""],
  ["amanda freitag", "https://drive.google.com/file/d/1EMbfT6YWUTorCOAfE5A1x2WP2kcNdPK0/view\nhttps://drive.google.com/file/d/13cRnHYjQ7UgDmYj4u-Oofp596kVKSbjA/view", ""],
  ["christian freitag", "https://drive.google.com/file/d/1BAFIuo9DxbT1IS9pdW3T2B5B2TirEq4y/view", ""],
  ["christina rockley", "https://drive.google.com/file/d/1xxDHfwtbn2Rc1l5TQILncpn2hmwUEUtx/view", ""],
  ["adrienne fleck", "https://drive.google.com/file/d/1hyaSssSR9viNHg-QSdhCDyMZGRCXKlLj/view", ""],
  ["matthew zweifel", "https://drive.google.com/file/d/13Hae9npBEZ5ZfAsBeCZz_rN44auUDdBz/view", ""],
  ["michele dill", "https://drive.google.com/file/d/1egG5sEql83Zjai-CXGw-JO5TdvHZoEGW/view", ""],
  ["katherine eickhorst", "https://drive.google.com/file/d/1OHCraimQgyzkWXzPJz57SmFzSyaodj7H/view", ""],
  ["fred fulks", "https://drive.google.com/file/d/10RBKrvIRJrfE61RsH32P1x2OsmsNI-QH/view", ""],
  ["carl jemison", "https://drive.google.com/file/d/1GO4eat2PQOv18vxVkKHVhU0uwpKmuHDZ/view", ""],
  ["james masterson", "https://drive.google.com/file/d/1zPcAalTdAVdKJhSOnyzo1-I0z_jhPN6r/view", ""],
  ["taylor penrod", "https://drive.google.com/file/d/1aSYda03OaziRF5Zw9QlwJWeWv4PJqcfw/view", ""],
  ["terry seufferlein", "https://drive.google.com/file/d/1E0aMz84xH_hXJfQ6WluaIdDGrnwFK6Gh/view", ""],
  ["teresa showen", "https://drive.google.com/file/d/16-qRm7sSfNPFG1juFs2lUtEcfdkUs5uI/view", ""],
  ["nikki wiarda", "https://drive.google.com/file/d/1_FVwg2X8L5p4RpiuEy3D-GLF_7Hlbtlj/view", ""],
  ["leslee trotter", "https://drive.google.com/file/d/1ej9oajCXdNGPvJ1RNWrYRewmsSjfilIm/view", ""],
  ["samantha wilson", "https://drive.google.com/file/d/1wpAAUNPK9AYNDfnb5cMW9YhHbxYwS-om/view", ""],
  ["scott abraham", "https://drive.google.com/file/d/1HaOEa5CF44A2DKsxrKTry1iolyrb_kps/view", ""],
  ["beth abraham", "https://drive.google.com/file/d/1HaOEa5CF44A2DKsxrKTry1iolyrb_kps/view", ""],
  ["jim baumann", "https://drive.google.com/file/d/1v0R52C1BdlNRcgglKC1ySKvJdoul8j-O/view", ""],
  ["kathy baumann", "https://drive.google.com/file/d/1v0R52C1BdlNRcgglKC1ySKvJdoul8j-O/view", ""],
  ["jamie wilson", "https://drive.google.com/file/d/1dRkkROy-lTpg9y945A9wjGDEQslYCE37/view", ""],
  ["michael wilson", "https://drive.google.com/file/d/1dRkkROy-lTpg9y945A9wjGDEQslYCE37/view", ""],
  ["natasha klutts", "https://drive.google.com/file/d/1U7Mo8LQRf_uwxKWNkEg3lpEPRjBNLBYi/view", ""],
  ["robert klutts", "https://drive.google.com/file/d/1U7Mo8LQRf_uwxKWNkEg3lpEPRjBNLBYi/view", ""],
  ["jesse salmon", "https://drive.google.com/file/d/1gV6-5IxvGwAHypLu9908K3pxpeY92XSt/view\nhttps://drive.google.com/file/d/1UfnPE0uAXbyMPMP371HcxFGQY-qEB-Io/view", ""],
  ["carolyn salmon", "https://drive.google.com/file/d/1gV6-5IxvGwAHypLu9908K3pxpeY92XSt/view", ""],
  ["trina nudson", "https://drive.google.com/file/d/1vM76Je5qzagq3dSvXsdfhazxG3s_6jg2/view", ""],
  ["jessica newman", "https://drive.google.com/file/d/1yAw34o6Qnd47JWrapQgixGSkr00AZGFj/view", ""],
  ["kate salmon", "https://drive.google.com/file/d/1UfnPE0uAXbyMPMP371HcxFGQY-qEB-Io/view", ""],
  ["chanille witham", "https://drive.google.com/file/d/1DwqnQaDvIwhmsGTUvAuOCIMjtnjisbpq/view", ""],
  ["peter witham", "https://drive.google.com/file/d/1DwqnQaDvIwhmsGTUvAuOCIMjtnjisbpq/view", ""],
  ["michael jackson", "https://drive.google.com/file/d/19j0Kg5H7ej4DrGI_YNItWlbkvTfxQpsv/view", ""],
  ["midtown psychological services", "https://drive.google.com/file/d/1o1Uu_Auc8hOoWdWoq68o9OjqH2_1UyIw/view", ""],
  ["gregory sisk", "https://drive.google.com/file/d/1qoeQ8Zac36lL6yDQY6dAKlnqUk9wyAK6/view", ""],
  ["helen weiser", "https://drive.google.com/file/d/1fCanjK-kt0CnyG9mkPNKpB6ETFsA5XHq/view", ""],
  ["april demasters", "https://drive.google.com/file/d/1SgxmnXX1GZGymX54EsJVcno92bTleJZV/view", ""],
  ["brooke gipson", "https://drive.google.com/file/d/1eQuImoYK90gezmSVXhv6t3fyqZM1HNdP/view", ""],
  ["terri gilbert", "https://drive.google.com/file/d/13LDafOE4TC3kcu_t7LtIBJbPu19WDS6z/view", ""],
  ["heather mcbride", "https://drive.google.com/file/d/1EegUjwC9cUWDpWf2GCtBzcICyQELBFwR/view", ""],
  ["ryan weber", "https://drive.google.com/file/d/18_Emk_hVteooBere2JJHPgllV_AaXh0H/view", ""],
  ["stephanie reed", "https://drive.google.com/file/d/1MKtLxNubdXvmirPTcsFEntliWOGqRumk/view", ""],
  ["tyler brown", "https://drive.google.com/file/d/13rr22SsLy83tVz_4XrFS4f_2e-MEjiI4/view", ""],
  ["jozef hanratty", "https://drive.google.com/file/d/1DQWQ6_wbWKEWXgCt8CT7EMzPPAcXw6TB/view?usp=drive_link", ""],
  ["kelly truelove", "https://drive.google.com/file/d/19lrK72LEXBztOlGJcpqneH8UxPg5D33H/view?usp=drive_link", ""],
  ["zach stangl", "https://drive.google.com/file/d/1LlQ4rJMfZDkylMlBdeLgtWCA73B-ZJ08/view?usp=drive_link", ""],

    ["Are Black women mean", "If you feel like all Black women are mean, your experience indicates you lack melanin inside your patriarch environment and you need more exposure", ""]
);